const { EmbedBuilder, AttachmentBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle, ChannelType } = require('discord.js');
const factory = require('../../core/factory');
const path = require('path');
const AdmZip = require('adm-zip');
const fs = require('fs-extra');

module.exports = {
    name: 'interactionCreate',
    async execute(interaction, client) {
        if (interaction.isChatInputCommand()) {
            const command = client.commands.get(interaction.commandName);
            if (!command) return;
            try {
                await command.run(interaction);
            } catch (error) {
                console.error(error);
                await interaction.reply({ content: 'Orbit error: Failed to execute command.', ephemeral: true });
            }
        }

        if (interaction.isModalSubmit()) {
            if (interaction.customId === 'manufacture_modal') {
                const name = interaction.fields.getTextInputValue('plugin_name');
                const prompt = interaction.fields.getTextInputValue('plugin_prompt');
                const id = name.toLowerCase().replace(/ /g, '-');

                await interaction.reply({ 
                    content: `🏗️ ${'MANUFACTURING STARTED:'.bold} Jupiter is dreaming up your **${name}** plugin...`, 
                    ephemeral: true 
                });

                try {
                    // 1. Generate the plugin
                    const options = {
                        name,
                        id,
                        description: 'AI Generated by Jupiter Factory',
                        author: interaction.user.tag,
                        version: '1.0.0',
                        aiPrompt: prompt,
                        outputDir: path.join(__dirname, '../../../output')
                    };

                    const pluginPath = await factory.generate(options);

                    // 2. Package into ZIP
                    const zip = new AdmZip();
                    zip.addLocalFolder(pluginPath);
                    const zipBuffer = zip.toBuffer();
                    const attachment = new AttachmentBuilder(zipBuffer, { name: `${id}.zip` });

                    // 3. Final Success Message
                    const embed = new EmbedBuilder()
                        .setTitle(`📦 Plugin Manufactured: ${name}`)
                        .setDescription(`Jupiter has completed the production of your plugin. You can now download it and install it on your Moon (Callisto).`)
                        .addFields(
                            { name: 'Plugin ID', value: `\`${id}\``, inline: true },
                            { name: 'Architect', value: interaction.user.tag, inline: true }
                        )
                        .setColor('#00ffff')
                        .setTimestamp();

                    let marketplaceChannel = interaction.guild.channels.cache.find(c => c.name === '🛒-plugin-market');
                    if (!marketplaceChannel) {
                        const factoryCategory = interaction.guild.channels.cache.find(c => c.type === ChannelType.GuildCategory && c.name.includes('THE FACTORY'));
                        marketplaceChannel = await interaction.guild.channels.create({
                            name: '🛒-plugin-market',
                            type: ChannelType.GuildText,
                            parent: factoryCategory ? factoryCategory.id : null,
                            topic: 'Jupiter Plugin Marketplace - Click to deploy plugins directly to your Moons!'
                        });
                    }

                    const installRow = new ActionRowBuilder()
                        .addComponents(
                            new ButtonBuilder()
                                .setCustomId(`install_plugin_${id}_europa`)
                                .setLabel('Install to Europa')
                                .setStyle(ButtonStyle.Success)
                                .setEmoji('🚀')
                        );

                    await marketplaceChannel.send({
                        embeds: [embed],
                        components: [installRow]
                    });

                    await interaction.followUp({ 
                        content: `✅ Plugin successfully manufactured! Check ${marketplaceChannel} to install it.`, 
                        files: [attachment],
                        ephemeral: true 
                    });

                } catch (error) {
                    console.error("Manufacturing Error:", error);
                    await interaction.followUp({ 
                        content: `❌ ${'MANUFACTURING FAILED:'.bold} Jupiter's cores overheated. Error: ${error.message}`, 
                        ephemeral: true 
                    });
                }
            }

            if (interaction.customId === 'manufacture_bot_modal') {
                const name = interaction.fields.getTextInputValue('bot_name');
                const desc = interaction.fields.getTextInputValue('bot_desc');
                const id = name.toLowerCase().replace(/ /g, '-');

                await interaction.reply({ 
                    content: `🌌 ${'ENGINE CONSTRUCTION STARTED:'.bold} Jupiter is building the **${name}** Core Engine...`, 
                    ephemeral: true 
                });

                try {
                    const engineFactory = require('../../core/engineFactory');
                    const options = {
                        name,
                        id,
                        description: desc,
                        author: interaction.user.tag,
                        version: '1.0.0',
                        outputDir: path.join(__dirname, '../../../output')
                    };

                    const enginePath = await engineFactory.generate(options);

                    const zip = new AdmZip();
                    zip.addLocalFolder(enginePath);
                    const zipBuffer = zip.toBuffer();
                    const attachment = new AttachmentBuilder(zipBuffer, { name: `${id}-engine.zip` });

                    const embed = new EmbedBuilder()
                        .setTitle(`🚀 Engine Constructed: ${name}`)
                        .setDescription(`Jupiter has finalized the core engine for **${name}**. This bot is now ready for deployment.`)
                        .addFields(
                            { name: 'System ID', value: `\`${id}\``, inline: true },
                            { name: 'Architect', value: interaction.user.tag, inline: true }
                        )
                        .setColor('#ffff00')
                        .setTimestamp();

                    await interaction.followUp({ 
                        embeds: [embed], 
                        files: [attachment],
                        ephemeral: true 
                    });

                } catch (error) {
                    console.error("Engine Error:", error);
                    await interaction.followUp({ 
                        content: `❌ ${'ENGINE FAILURE:'.bold} Jupiter's manufacturing line stalled. Error: ${error.message}`, 
                        ephemeral: true 
                    });
                }
            }
        }

        if (interaction.isButton()) {
            if (interaction.customId.startsWith('install_plugin_')) {
                const parts = interaction.customId.split('_');
                const moonId = parts.pop();
                const pluginId = parts.slice(2).join('_');

                await interaction.reply({ content: `📡 Initiating Stellar Beam for **\${pluginId}** to **\${moonId}**...`, ephemeral: true });

                try {
                    const dockingStation = require('../../core/DockingStation');
                    const pluginPath = path.join(__dirname, '../../../output', pluginId);
                    
                    if (!fs.existsSync(pluginPath)) {
                        throw new Error(`Plugin data not found at \${pluginPath}`);
                    }

                    const getAllFiles = (dir, fileList = []) => {
                        const files = fs.readdirSync(dir);
                        for (const file of files) {
                            const stat = fs.statSync(path.join(dir, file));
                            if (stat.isDirectory()) {
                                getAllFiles(path.join(dir, file), fileList);
                            } else {
                                fileList.push(path.join(dir, file));
                            }
                        }
                        return fileList;
                    };

                    const files = {};
                    const filePaths = getAllFiles(pluginPath);
                    for (const fullPath of filePaths) {
                        const relativePath = path.relative(pluginPath, fullPath);
                        files[relativePath] = await fs.readFile(fullPath, 'utf8');
                    }

                    await dockingStation.beamPlugin(moonId, pluginId, files);
                    
                    await interaction.followUp({ content: `✅ **\${pluginId}** successfully beamed to **\${moonId}**!`, ephemeral: true });
                } catch (error) {
                    console.error("Beam Error:", error);
                    await interaction.followUp({ content: `❌ Beam failed: \${error.message}`, ephemeral: true });
                }
            }
        }
    }
};
