const { EmbedBuilder, AttachmentBuilder } = require('discord.js');
const factory = require('../../core/factory');
const path = require('path');
const AdmZip = require('adm-zip');
const fs = require('fs-extra');

module.exports = {
    name: 'interactionCreate',
    async execute(interaction, client) {
        if (interaction.isChatInputCommand()) {
            const command = client.commands.get(interaction.commandName);
            if (!command) return;
            try {
                await command.run(interaction);
            } catch (error) {
                console.error(error);
                await interaction.reply({ content: 'Orbit error: Failed to execute command.', ephemeral: true });
            }
        }

        if (interaction.isModalSubmit()) {
            if (interaction.customId === 'manufacture_modal') {
                const name = interaction.fields.getTextInputValue('plugin_name');
                const prompt = interaction.fields.getTextInputValue('plugin_prompt');
                const id = name.toLowerCase().replace(/ /g, '-');

                await interaction.reply({ 
                    content: `🏗️ ${'MANUFACTURING STARTED:'.bold} Jupiter is dreaming up your **${name}** plugin...`, 
                    ephemeral: true 
                });

                try {
                    // 1. Generate the plugin
                    const options = {
                        name,
                        id,
                        description: 'AI Generated by Jupiter Factory',
                        author: interaction.user.tag,
                        version: '1.0.0',
                        aiPrompt: prompt,
                        outputDir: path.join(__dirname, '../../../output')
                    };

                    const pluginPath = await factory.generate(options);

                    // 2. Package into ZIP
                    const zip = new AdmZip();
                    zip.addLocalFolder(pluginPath);
                    const zipBuffer = zip.toBuffer();
                    const attachment = new AttachmentBuilder(zipBuffer, { name: `${id}.zip` });

                    // 3. Final Success Message
                    const embed = new EmbedBuilder()
                        .setTitle(`📦 Plugin Manufactured: ${name}`)
                        .setDescription(`Jupiter has completed the production of your plugin. You can now download it and install it on your Moon (Callisto).`)
                        .addFields(
                            { name: 'Plugin ID', value: `\`${id}\``, inline: true },
                            { name: 'Architect', value: interaction.user.tag, inline: true }
                        )
                        .setColor('#00ffff')
                        .setTimestamp();

                    await interaction.followUp({ 
                        embeds: [embed], 
                        files: [attachment],
                        ephemeral: true 
                    });

                } catch (error) {
                    console.error("Manufacturing Error:", error);
                    await interaction.followUp({ 
                        content: `❌ ${'MANUFACTURING FAILED:'.bold} Jupiter's cores overheated. Error: ${error.message}`, 
                        ephemeral: true 
                    });
                }
            }

            if (interaction.customId === 'manufacture_bot_modal') {
                const name = interaction.fields.getTextInputValue('bot_name');
                const desc = interaction.fields.getTextInputValue('bot_desc');
                const id = name.toLowerCase().replace(/ /g, '-');

                await interaction.reply({ 
                    content: `🌌 ${'ENGINE CONSTRUCTION STARTED:'.bold} Jupiter is building the **${name}** Core Engine...`, 
                    ephemeral: true 
                });

                try {
                    const engineFactory = require('../../core/engineFactory');
                    const options = {
                        name,
                        id,
                        description: desc,
                        author: interaction.user.tag,
                        version: '1.0.0',
                        outputDir: path.join(__dirname, '../../../output')
                    };

                    const enginePath = await engineFactory.generate(options);

                    const zip = new AdmZip();
                    zip.addLocalFolder(enginePath);
                    const zipBuffer = zip.toBuffer();
                    const attachment = new AttachmentBuilder(zipBuffer, { name: `${id}-engine.zip` });

                    const embed = new EmbedBuilder()
                        .setTitle(`🚀 Engine Constructed: ${name}`)
                        .setDescription(`Jupiter has finalized the core engine for **${name}**. This bot is now ready for deployment.`)
                        .addFields(
                            { name: 'System ID', value: `\`${id}\``, inline: true },
                            { name: 'Architect', value: interaction.user.tag, inline: true }
                        )
                        .setColor('#ffff00')
                        .setTimestamp();

                    await interaction.followUp({ 
                        embeds: [embed], 
                        files: [attachment],
                        ephemeral: true 
                    });

                } catch (error) {
                    console.error("Engine Error:", error);
                    await interaction.followUp({ 
                        content: `❌ ${'ENGINE FAILURE:'.bold} Jupiter's manufacturing line stalled. Error: ${error.message}`, 
                        ephemeral: true 
                    });
                }
            }
        }
    }
};
