const { EmbedBuilder, AttachmentBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle, ChannelType, StringSelectMenuBuilder, StringSelectMenuOptionBuilder } = require('discord.js');
const factory = require('../../core/factory');
const path = require('path');
const AdmZip = require('adm-zip');
const fs = require('fs-extra');

module.exports = {
    name: 'interactionCreate',
    async execute(interaction, client) {
        if (interaction.isChatInputCommand()) {
            const command = client.commands.get(interaction.commandName);
            if (!command) return;
            try {
                await command.run(interaction);
            } catch (error) {
                console.error(error);
                await interaction.reply({ content: 'Orbit error: Failed to execute command.', ephemeral: true });
            }
        }

        if (interaction.isModalSubmit()) {
            if (interaction.customId === 'manufacture_modal') {
                const name = interaction.fields.getTextInputValue('plugin_name');
                const prompt = interaction.fields.getTextInputValue('plugin_prompt');
                const id = name.toLowerCase().replace(/ /g, '-');

                await interaction.reply({ 
                    content: `🏗️ ${'MANUFACTURING STARTED:'.bold} Jupiter is dreaming up your **${name}** plugin...`, 
                    ephemeral: true 
                });

                try {
                    // 1. Generate the plugin
                    const options = {
                        name,
                        id,
                        description: 'AI Generated by Jupiter Factory',
                        author: interaction.user.tag,
                        version: '1.0.0',
                        aiPrompt: prompt,
                        outputDir: path.join(__dirname, '../../../output')
                    };

                    const pluginPath = await factory.generate(options);

                    // 2. Package into ZIP
                    const zip = new AdmZip();
                    zip.addLocalFolder(pluginPath);
                    const zipBuffer = zip.toBuffer();
                    const attachment = new AttachmentBuilder(zipBuffer, { name: `${id}.zip` });

                    // 3. Final Success Message
                    const embed = new EmbedBuilder()
                        .setTitle(`📦 Plugin Manufactured: ${name}`)
                        .setDescription(prompt.length > 200 ? prompt.substring(0, 197) + '...' : prompt)
                        .addFields(
                            { name: 'Plugin ID', value: `\`${id}\``, inline: true },
                            { name: 'Architect', value: interaction.user.tag, inline: true },
                            { name: 'Version', value: '1.0.0', inline: true }
                        )
                        .setColor('#00ffff')
                        .setTimestamp();

                    let marketplaceChannel = interaction.guild.channels.cache.find(c => c.name === '🛒-plugin-market');
                    if (!marketplaceChannel) {
                        const factoryCategory = interaction.guild.channels.cache.find(c => c.type === ChannelType.GuildCategory && c.name.includes('THE FACTORY'));
                        marketplaceChannel = await interaction.guild.channels.create({
                            name: '🛒-plugin-market',
                            type: ChannelType.GuildText,
                            parent: factoryCategory ? factoryCategory.id : null,
                            topic: 'Jupiter Plugin Marketplace - Click to deploy plugins directly to your Moons!'
                        });
                    }

                    const actionRow = new ActionRowBuilder()
                        .addComponents(
                            new ButtonBuilder()
                                .setCustomId(`deploy_plugin_${id}`)
                                .setLabel('Deploy 🚀')
                                .setStyle(ButtonStyle.Primary),
                            new ButtonBuilder()
                                .setCustomId(`download_plugin_${id}`)
                                .setLabel('Download 💾')
                                .setStyle(ButtonStyle.Secondary)
                        );

                    await marketplaceChannel.send({
                        embeds: [embed],
                        components: [actionRow]
                    });

                    await interaction.followUp({ 
                        content: `✅ Plugin successfully manufactured! Check ${marketplaceChannel} to deploy or download it.`, 
                        files: [attachment],
                        ephemeral: true 
                    });

                } catch (error) {
                    console.error("Manufacturing Error:", error);
                    await interaction.followUp({ 
                        content: `❌ ${'MANUFACTURING FAILED:'.bold} Jupiter's cores overheated. Error: ${error.message}`, 
                        ephemeral: true 
                    });
                }
            }

            if (interaction.customId === 'manufacture_bot_modal') {
                const name = interaction.fields.getTextInputValue('bot_name');
                const desc = interaction.fields.getTextInputValue('bot_desc');
                const id = name.toLowerCase().replace(/ /g, '-');

                await interaction.reply({ 
                    content: `🌌 ${'ENGINE CONSTRUCTION STARTED:'.bold} Jupiter is building the **${name}** Core Engine...`, 
                    ephemeral: true 
                });

                try {
                    const engineFactory = require('../../core/engineFactory');
                    const options = {
                        name,
                        id,
                        description: desc,
                        author: interaction.user.tag,
                        version: '1.0.0',
                        outputDir: path.join(__dirname, '../../../output')
                    };

                    const enginePath = await engineFactory.generate(options);

                    const zip = new AdmZip();
                    zip.addLocalFolder(enginePath);
                    const zipBuffer = zip.toBuffer();
                    const attachment = new AttachmentBuilder(zipBuffer, { name: `${id}-engine.zip` });

                    const embed = new EmbedBuilder()
                        .setTitle(`🚀 Engine Constructed: ${name}`)
                        .setDescription(`Jupiter has finalized the core engine for **${name}**. This bot is now ready for deployment.`)
                        .addFields(
                            { name: 'System ID', value: `\`${id}\``, inline: true },
                            { name: 'Architect', value: interaction.user.tag, inline: true }
                        )
                        .setColor('#ffff00')
                        .setTimestamp();

                    await interaction.followUp({ 
                        embeds: [embed], 
                        files: [attachment],
                        ephemeral: true 
                    });

                } catch (error) {
                    console.error("Engine Error:", error);
                    await interaction.followUp({ 
                        content: `❌ ${'ENGINE FAILURE:'.bold} Jupiter's manufacturing line stalled. Error: ${error.message}`, 
                        ephemeral: true 
                    });
                }
            }
        }

        if (interaction.isButton()) {
            const dockingStation = require('../../core/DockingStation');

            if (interaction.customId.startsWith('deploy_plugin_')) {
                const pluginId = interaction.customId.replace('deploy_plugin_', '');
                const moons = Array.from(dockingStation.moons.keys());

                if (moons.length === 0) {
                    return interaction.reply({ content: '❌ No Moons are currently docked. Beam is offline.', ephemeral: true });
                }

                const selectMenu = new StringSelectMenuBuilder()
                    .setCustomId(`select_moon_${pluginId}`)
                    .setPlaceholder('Select a Moon to beam the plugin to...')
                    .addOptions(
                        moons.map(moon => 
                            new StringSelectMenuOptionBuilder()
                                .setLabel(moon.charAt(0).toUpperCase() + moon.slice(1))
                                .setValue(moon)
                                .setEmoji('🌑')
                        )
                    );

                const row = new ActionRowBuilder().addComponents(selectMenu);

                await interaction.reply({ 
                    content: `📡 Select a target for **${pluginId}**:`, 
                    components: [row], 
                    ephemeral: true 
                });
            }

            if (interaction.customId.startsWith('download_plugin_')) {
                const pluginId = interaction.customId.replace('download_plugin_', '');
                const pluginPath = path.join(__dirname, '../../../output', pluginId);

                if (!fs.existsSync(pluginPath)) {
                    return interaction.reply({ content: '❌ Plugin source not found on this station.', ephemeral: true });
                }

                await interaction.reply({ content: '📦 Packaging plugin for download...', ephemeral: true });

                const zip = new AdmZip();
                zip.addLocalFolder(pluginPath);
                const buffer = zip.toBuffer();
                const attachment = new AttachmentBuilder(buffer, { name: `${pluginId}.zip` });

                await interaction.followUp({ 
                    content: `💾 Here is your plugin package for **${pluginId}**:`, 
                    files: [attachment], 
                    ephemeral: true 
                });
            }
        }

        if (interaction.isStringSelectMenu()) {
            if (interaction.customId.startsWith('select_moon_')) {
                const pluginId = interaction.customId.replace('select_moon_', '');
                const moonId = interaction.values[0];

                await interaction.update({ content: `📡 Initiating Stellar Beam for **${pluginId}** to **${moonId}**...`, components: [] });

                try {
                    const dockingStation = require('../../core/DockingStation');
                    const pluginPath = path.join(__dirname, '../../../output', pluginId);
                    
                    const getAllFiles = (dir, fileList = []) => {
                        const files = fs.readdirSync(dir);
                        for (const file of files) {
                            const stat = fs.statSync(path.join(dir, file));
                            if (stat.isDirectory()) {
                                getAllFiles(path.join(dir, file), fileList);
                            } else {
                                fileList.push(path.join(dir, file));
                            }
                        }
                        return fileList;
                    };

                    const files = {};
                    const filePaths = getAllFiles(pluginPath);
                    for (const fullPath of filePaths) {
                        const relativePath = path.relative(pluginPath, fullPath);
                        files[relativePath] = await fs.readFile(fullPath, 'utf8');
                    }

                    await dockingStation.beamPlugin(moonId, pluginId, files);
                    
                    await interaction.followUp({ content: `✅ **${pluginId}** successfully beamed to **${moonId}**!`, ephemeral: true });
                } catch (error) {
                    console.error("Beam Error:", error);
                    await interaction.followUp({ content: `❌ Beam failed: ${error.message}`, ephemeral: true });
                }
            }
        }
    }
};
